@startuml
class Feedback{
-user: String
-Date: Date
-ResponseDataId: int
+Feedback(String, Date, int)
}

class ResponseData{
-ResponseDataId: int
-Questions: ArrayList<Integer>
+ResponseData(int, ArrayList)
}

class Questions{
-QuestionId: int
-Question_No: int
-Response: int
+Questions(int, int, int)
}

class AllQuestions{
-Question_No: int
-Question: string
+getQuestion(int)
}
Feedback <|-- ResponseData
ResponseData *-- Questions
@enduml